general.live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = false
transparent_background_colors = true

[colors.bright]
black = "0x7d7a68"
blue = "0x999580"
cyan = "0xd43552"
green = "0x292824"
magenta = "0xe8e4cf"
red = "0xb65611"
white = "0xfefbec"
yellow = "0x6e6b5e"

[colors.cursor]
cursor = "0xa6a28c"
text = "0x20201d"

[colors.normal]
black = "0x20201d"
blue = "0x6684e1"
cyan = "0x1fad83"
green = "0x60ac39"
magenta = "0xb854d4"
red = "0xd73737"
white = "0xa6a28c"
yellow = "0xae9513"

[colors.primary]
background = "0x20201d"
foreground = "0xa6a28c"

[cursor]
style = "Beam"
thickness = 0.15
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[font]
normal.family = "Hack Nerd Font"
size = 13.0


[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[selection]
semantic_escape_chars = ",│`|:\"' ()[]{}<>"

[window]
decorations = "full"
opacity = 0.95
title = "Alacritty"

[window.dimensions]
columns = 160
lines = 50

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
